In [1]:
import torch
torch.__version__

'2.10.0+cu128'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()
# 从只包含一个元素的张量中读取元素

7

In [5]:
vector =  torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
# 用tensor.ndim 张量对象.属性方式 获取张量的维度信息
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8, 9],
            [9, 10, 11]])
MATRIX

tensor([[ 7,  8,  9],
        [ 9, 10, 11]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 3])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
             [3, 6, 9],
             [2, 4, 5]],
             [[1, 2, 3],
             [3, 6, 9],
             [2, 4, 5]]  ])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([2, 3, 3])

In [14]:
# 创建随机张量
# torch.rand(size = )
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.4834, 0.2135, 0.9280, 0.6000],
         [0.8707, 0.1994, 0.6389, 0.7810],
         [0.6400, 0.3560, 0.7680, 0.5937]]),
 torch.float32)

In [15]:
random_T = torch.rand(size=(224,224,3))
random_T.shape,random_T.ndim,random_T

(torch.Size([224, 224, 3]),
 3,
 tensor([[[0.6267, 0.1802, 0.0949],
          [0.2729, 0.0646, 0.4055],
          [0.8667, 0.1174, 0.5397],
          ...,
          [0.5218, 0.1151, 0.7124],
          [0.3709, 0.3445, 0.0124],
          [0.1856, 0.1841, 0.5885]],
 
         [[0.2618, 0.6439, 0.4129],
          [0.5044, 0.6547, 0.5963],
          [0.1846, 0.4804, 0.1055],
          ...,
          [0.1171, 0.2682, 0.5949],
          [0.7958, 0.5855, 0.8742],
          [0.3300, 0.0113, 0.6977]],
 
         [[0.5885, 0.9130, 0.4468],
          [0.7823, 0.3803, 0.5253],
          [0.7782, 0.8763, 0.3373],
          ...,
          [0.6975, 0.9463, 0.4790],
          [0.3894, 0.3942, 0.3112],
          [0.4328, 0.0709, 0.5666]],
 
         ...,
 
         [[0.0071, 0.6095, 0.0277],
          [0.6678, 0.4000, 0.8150],
          [0.6638, 0.1023, 0.0446],
          ...,
          [0.1517, 0.9843, 0.7763],
          [0.3695, 0.3967, 0.6501],
          [0.7027, 0.4010, 0.0608]],
 
         [[0.603

In [16]:
# 创建一个全为0的张量
zeros = torch.zeros(size = (3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size = (3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten_deprecated = torch.range(0,10)
zero_to_ten_deprecated

/tmp/ipykernel_36770/1801371773.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
zero_to_ten.ndim, zero_to_ten.shape, zero_to_ten.dtype

(1, torch.Size([10]), torch.int64)

In [21]:
# 创建一个与input张量形状相同的张量
# torch.zeros_like(input = tensor())  torch.ones_like(input)
ten_zeros = torch.zeros_like(input = zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                device=None, # defaults to None, which uses the default tensor type
                requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [24]:
float_16_tensor = torch.tensor([1, 2, 3],
                dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [25]:
some_tensor = torch.rand(size = (3,4))
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.5336, 0.9233, 0.1975, 0.0028],
        [0.2762, 0.0130, 0.9580, 0.0027],
        [0.0815, 0.1521, 0.8995, 0.5170]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


In [26]:
tensor = torch.tensor([1, 2, 3])
tensor.dtype

torch.int64

In [27]:
tensor + 10

tensor([11, 12, 13])

In [28]:
tensor * 10

tensor([10, 20, 30])

In [29]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [30]:
tensor += 10
tensor

tensor([1, 2, 3])

In [31]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [32]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
# 内积
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [34]:
tensor.shape

torch.Size([3])

In [35]:
tensor * tensor

tensor([1, 4, 9])

In [36]:
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
tensor @ tensor

tensor(14)

In [38]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 0 ns, sys: 379 μs, total: 379 μs
Wall time: 479 μs


tensor(14)

In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 141 μs, sys: 0 ns, total: 141 μs
Wall time: 216 μs


tensor(14)

In [40]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [41]:
# torch.matmul(tensor_A, tensor_B) # (this will error)
# 

In [42]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [43]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [44]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [45]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [46]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [47]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [48]:
torch.manual_seed(30)

linear = torch.nn.Linear(in_features = 2,
              out_features = 7)

x = tensor_A
output = linear(x)
# output = x * [in_features, out_features]
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[0.8037, 0.7945, 1.7621, 0.2596, 0.3174, 0.9601, 0.8340],
        [2.6340, 1.7714, 3.2450, 1.7259, 1.0802, 1.9884, 1.6854],
        [4.4643, 2.7483, 4.7278, 3.1922, 1.8430, 3.0167, 2.5367]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 7])


In [49]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [51]:
tensor = torch.arange(10, 100, 10)
print(f'Tensor:{tensor}')

print(f'Index where tensor is max: {tensor.argmax()}')
print(f'Index where tensor is min: {tensor.argmin()}')


Tensor:tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where tensor is max: 8
Index where tensor is min: 0


小结:

import torch


---


创建tensor的方法:

创建单个元素

scalar = torch.tensor(7)

创建向量

vector = torch.tensor([3,4])

创建矩阵

MARTIX = torch.tensor([[1, 2],
            [3, 4]])

创建张量

TENSOR = torch.tensor([[[1,2,3],
             [3,6,9],
             [2,4,5]]])

创建指定形状的随机张量

rand_tensor = torch.rand(size = (3,4))

创建全0的张量

zeros_tensor = torch.zeros(size = (3,4))

创建全1的张量

ones_tensor = torch.ones(size = (3,4))

创建一个与输入张量形状相同的张量

shape_tensor = torch.zeros_like(input))


---


tensor的属性:

tensor.ndim 查看tensor维度

tensor.shape 查看tensor形状

tensor.dtype 查看tensor中数据类型

tensor.device 查看tensor设备类型(CPU/GPU)




---

tensor的运算:

+、-、*、/

矩阵乘法 torch.matmul(tensor1, tensor2)

矩阵转置 tensor_A.T






In [52]:
import torch
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [53]:
x_reshaped = x.reshape(1,8)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [54]:
y_reshaped = x_reshaped.reshape(2,4)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [55]:
z = x.view(4, 2)
z, z.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]),
 torch.Size([4, 2]))

In [56]:
z[:,0] = 5
z,x

(tensor([[5., 2.],
         [5., 4.],
         [5., 6.],
         [5., 8.]]),
 tensor([5., 2., 5., 4., 5., 6., 5., 8.]))

In [57]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 5., 4., 5., 6., 5., 8.],
        [5., 2., 5., 4., 5., 6., 5., 8.],
        [5., 2., 5., 4., 5., 6., 5., 8.],
        [5., 2., 5., 4., 5., 6., 5., 8.]])

In [58]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 5., 4., 5., 6., 5., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([5., 2., 5., 4., 5., 6., 5., 8.])
New shape: torch.Size([8])


In [59]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 5., 4., 5., 6., 5., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 2., 5., 4., 5., 6., 5., 8.]])
New shape: torch.Size([1, 8])


In [60]:
# Create tensor with specific shape
x_original = torch.rand(size=(1, 2, 3, 4))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 3, 1) # shifts axis 0->1, 1->3, 2->0, 3->2

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([1, 2, 3, 4])
New shape: torch.Size([3, 1, 4, 2])


In [61]:
x_original,x_permuted

(tensor([[[[0.3163, 0.2989, 0.7827, 0.6531],
           [0.4221, 0.3149, 0.5815, 0.0656],
           [0.3457, 0.9641, 0.2490, 0.1174]],
 
          [[0.5926, 0.5136, 0.5753, 0.2062],
           [0.3758, 0.1805, 0.4670, 0.0496],
           [0.5757, 0.1479, 0.3457, 0.2162]]]]),
 tensor([[[[0.3163, 0.5926],
           [0.2989, 0.5136],
           [0.7827, 0.5753],
           [0.6531, 0.2062]]],
 
 
         [[[0.4221, 0.3758],
           [0.3149, 0.1805],
           [0.5815, 0.4670],
           [0.0656, 0.0496]]],
 
 
         [[[0.3457, 0.5757],
           [0.9641, 0.1479],
           [0.2490, 0.3457],
           [0.1174, 0.2162]]]]))

In [62]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
x = torch.rand(size = (2,3,3))
x

tensor([[[0.2715, 0.9695, 0.8297],
         [0.0435, 0.5178, 0.3274],
         [0.4208, 0.2368, 0.3516]],

        [[0.3636, 0.4537, 0.8158],
         [0.8184, 0.5022, 0.1390],
         [0.6871, 0.2544, 0.9488]]])

In [64]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[0.2715, 0.9695, 0.8297],
        [0.0435, 0.5178, 0.3274],
        [0.4208, 0.2368, 0.3516]])
Second square bracket: tensor([0.2715, 0.9695, 0.8297])
Third square bracket: 0.2714954614639282


In [65]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[0.2715, 0.9695, 0.8297],
        [0.3636, 0.4537, 0.8158]])

In [66]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[0.9695, 0.5178, 0.2368],
        [0.4537, 0.5022, 0.2544]])

In [67]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([0.5178, 0.5022])

In [68]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([0.2715, 0.9695, 0.8297])

In [69]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [70]:
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [71]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [72]:
# tensor = tensor + 1  # 这种写法，numpy_tensor不会随着tensor的值改变而改变
# tensor, numpy_tensor
# (tensor([3., 3., 3., 3., 3., 3., 3.]),
# array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

# tensor += 1
# tensor, numpy_tensor
# 如果先运行tensor += 1, 则numpy_tensor会随着tensor的值改变而改变
# 当运行过一次tensor = tensor + 1之后, numpy_tensor便不会随着tensor的值改变而改变


In [73]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5232, 0.9378, 0.1448, 0.9291],
        [0.1173, 0.8549, 0.6341, 0.4991],
        [0.5158, 0.8220, 0.2750, 0.4322]])

Tensor B:
tensor([[0.8771, 0.9301, 0.7586, 0.6401],
        [0.9802, 0.6769, 0.7497, 0.6752],
        [0.6840, 0.2927, 0.4769, 0.4271]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [74]:
import torch
# import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [75]:
!nvidia-smi

Thu Feb  5 17:03:34 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.57                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5060 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   51C    P4             17W /  106W |    1491MiB /   8151MiB |      9%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [76]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [77]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
# Count number of devices
torch.cuda.device_count()

1

In [79]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [80]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

In [ ]:
tensor_on_gpu